language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: nYGxaLqcJIEJQwSg9MvDFYMtjhRDGK+kx4SLBRIIywsUN6UMAntmvVtRmiRRZFAzZwHXedvTp/91ZoL1Q4avlc5SAoP5YIyIfFejAUOVyidSOsc8etAqz7qYJRtVNXL4njk0Igtig5MvOT54HEoEBKz2MgdFODsasLFOrPXGr1gVpHuSykaCeU0AqEDZon/LsrptBYiquPBMxa31OaxZJaOem8/ub7qAEaI6rxOEfc87thHAaQwC5uC8uK59JV2qzoWSyoeWm8w0+F26tHmOK8BbOGfaBoYQIJ8THF0g1dwGVcu4YYzW24R90MAqegQQ0LEk0p8QNPJe/k63A8KOIwZ9ZFHSrzAgcXQktrXS3abrbnGjdRAaSsvjGyU/fe5a3Pv9fBlDbciomun5ph9bcfdGmII4F9LjamiCQHOvo3jFlR08A1+004YzfFCH1NHarGHKRcgoYDU++JST7EBBN3YhqUwu4e3ds02jL6FCxOMKA6aTMdFPIfp+GR9EIlDpslv03OQ0h1nq6gLALb4+/S6Zvq87IanjfqPusDxjbs0omfei0Qsut25czks3RIrmOUrzl9ZzoJ9tpwnSYhrMpCYBwikDrelY1NNd206egs51sbLE6ZSwOs8lVSEKxwrjAB6UfWL7BehdE2qwaCIza8r3acFBNkNzR6roXysZsVg=
  app: colorations
  skip_cleanup: true